
# Main Types

- name: 🐛 Bug
  description: A bug report or a fix for one
  color: 'E9FD00'
  from_name: 'bug'

- name: ️🌟 Feature
  description: A feature request or an implementation of one
  color: 'FDD835'
  from_name: 'enhancement'

- name: 🤔 Question
  description: The issue is an open question
  color: '49472E'
  from_name: 'question'

# Secondary Types

- name: 👷 Automata
  description: Work on CI or other remote automation
  color: '4a97D6'

- name: 💥 Breaking Change
  description: Introduces an API breaking change
  color: 'E7681E'

- name: 🔨 Build
  description: Work on the build or packaging system
  color: 'BFDADC'

- name: 📝 Documentation
  description: Work on documentation
  color: '706F40'
  from_name: 'documentation'

- name: 🏗️ Infrastructure
  description: Work on deployments and cloud providers
  color: 'bfd4f2'

- name: 🐎️️ Performance
  description: Work on performance
  color: 'D56E64'

- name: ♻️ Refactoring
  description: Work on refactoring or reformatting code
  color: '409B44'

- name: ⛏️ Removal
  description: Removal or deprecation of things
  color: 'EE6C00'

- name: 🔒️ Security
  description: Work on information security
  color: '222222'

- name: 🛠 Tooling
  description: Work on developer scripts, lints or tests
  color: 'A06023'

- name: 🧹 Upkeep
  description: Updating dependencies or other maintenance
  color: 'BBB490'

- name: 💄 Visual
  description: Work on visual interfaces, styles or assets
  color: '930843'

# Maintainer Flow

- name: ⏳ Wait for Response
  description: Issue waiting for maintainer action
  color: '7057FF'

- name: 🔍 Wait for Investigation
  description: Issue being investigated by maintainers
  color: 'D876E3'

- name: 💭 Wait for Discussion
  description: Issue being discussed or under consideration
  color: 'D876E3'

- name: 👍️ Wait for PR
  description: Issue OK and waiting for implementation
  color: 'D876E3'

- name: 🪨 Blocked
  description: Waiting on another issue or something
  color: '99CCCC'

# Issue Priority

- name: 🚨 High Priority
  description: One of the utmost importance
  color: 'FF0000'

- name: 😎 Nice to Have
  description: The issue is awesome but not essential
  color: '020202'

# Closing Reasons (if other than done)

- name: ⚰️ Abandoned
  description: 'Acknowledged but #WontFix'
  color: 'AAAAAA'
  from_name: 'wontfix'

- name: 🧬 Duplicate
  description: This issue or pull request already exists
  color: '97A5BE'
  from_name: 'duplicate'

- name: 🙃 Invalid
  description: Acknowledged but something seems wrong
  color: 'AAAAAA'
  from_name: 'invalid'

# Call-outs

- name: 👋 Good First Issue
  description: A good issue for new contributors
  color: 'B1FC6F'
  from_name: 'good first issue'

- name: 💁 Help Appreciated
  description: Additional helping hands welcome!
  color: '00FFFF'
  from_name: 'help wanted'

- name: 🤖 Robot
  description: Done by automation
  color: '8A9DA6'

- name: 🥷 Stealth
  description: Not mentioned in the changelogs
  color: '111111'
