categories:

  - title: 💥 Breaking Changes
    label: 💥 Breaking Change

  - title: ️🌟 New Features
    label: ️🌟 Feature

  - title: 🐛 Fixes
    label: 🐛 Bug

  - title: 🔒️ Security
    label: 🔒️ Security

  - title: 🐎️️ Performance
    label: 🐎️️ Performance

  - title: 📝 Documentation
    label: 📝 Documentation

  - title: 💄 Adornments
    label: 💄 Visual

  - title: 🧰️ Maintenance
    collapse-after: 3
    labels:
      - 👷 Automata
      - 🔨 Build
      - 🏗️ Infrastructure
      - ♻️ Refactoring
      - ⛏️ Removal
      - 🛠 Tooling
      - 🧹 Upkeep

exclude-labels:
  - 🥷 Stealth

exclude-contributors:
  - dependabot  # sorry bot 😢

version-resolver:
  default: patch
  major:
    labels:
      - 💥 Breaking Change
  minor:
    labels:
      - 🌟 Feature
  patch:
    labels: []


template: |
  $CHANGES


autolabeler:

  - label: 👷 Automata
    title:
      - '/CI/i'
      - '/GitHub/i'
      - '/workflow/i'
      - '/🐙/i'
      - '/👷/i'
    files:
      - '.github/**/*'

  - label: 🐛 Bug
    title:
      - '/bug/i'
      - '/correct/i'
      - '/fix/i'
      - '/🐛/i'
      - '/🐞/i'
      - '/🚨/i'
      - '/🩹/i'
      - '/🪲/i'

  - label: 🔨 Build
    title:
      - '/Dockerfile/i'
      - '/build/i'
      - '/🐋/i'
      - '/🐳/i'
      - '/🔨/i'

  - label: ️🌟 Feature
    title:
      - '/add/i'
      - '/create/i'
      - '/feature/i'
      - '/implement/i'
      - '/✨/i'
      - '/⭐️/i'
      - '/💫/i'
      - '/🚀/i'
      - '/️🌟/i'

  - label: 📝 Documentation
    title:
      - '/README/i'
      - '/docs/i'
      - '/documentation/i'
      - '/📒/i'
      - '/📓/i'
      - '/📚/i'
      - '/📝/i'
    files:
      - '*.md'
      - '*.rst'

  - label: ♻️ Refactoring
    title:
      - '/clean/i'
      - '/move/i'
      - '/refactor/i'
      - '/relocate/i'
      - '/rename/i'
      - '/rework/i'
      - '/♻️/i'
      - '/🎨/i'
      - '/🚚/i'

  - label: 🧹 Upkeep
    title:
      - '/bump/i'
      - '/dependencies/i'
      - '/ignore/i'
      - '/pin/i'
      - '/upgrade/i'
      - '/➕️️/i'
      - '/➖️️/i'
      - '/⬆️/i'
      - '/⬇️️/i'
      - '/🏷️/i'
      - '/📌/i'
      - '/🔖/i'
      - '/🙈/i'
      - '/🧹/i'

  - label: 🛠 Tooling
    title:
      - '/Makefile\i'
      - '/hook\i'
      - '/lint/i'
      - '/script\i'
      - '/test/i'
      - '/⚒️/i'
      - '/⚙️/i'
      - '/🔧/i'
      - '/🛠️/i'
      - '/🧑‍💻/i'
      - '/🧪/i'
      - '/🪝/i'

  - label: 💄 Visual
    files:
      - '*.gif'
      - '*.jpeg'
      - '*.jpg'
      - '*.png'
      - '*.svg'
