name: Define Labels

on:
  push:
    branches:
      - main
      - master
    paths:
      - .github/labels.yml

jobs:


  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run the labeler
        uses: crazy-max/ghaction-github-labeler@v4.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-delete: true
