name: labeling

on:
  push:
    branches:
      - main
      - master
    paths:
      - .github/labels.yml
      - .github/workflows/labeling.yml

jobs:


  label-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Synchronize GitHub labels
        uses: crazy-max/ghaction-github-labeler@v4.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-delete: true
