name: release-drafter

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
    types: [opened, reopened, synchronize]

jobs:


  release-draft-update:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
