name: release-drafter

on:

  # update release draft when master changes
  push:
    branches: [main, master]

  # label pull requests when they are opened
  # the original events also include 'synchronize' which triggers on PR HEAD change
  # and 'edited' which triggers on title change but both of the previous can be
  # quite annoying if you already set the labels properly after opening the PR
  pull_request:
    branches: [main, master]
    types: [opened, reopened]

permissions:
  contents: read

jobs:

  release-draft-update:
    permissions:
      contents: write       # for creating the release draft
      pull-requests: write  # for the autolabeler
    runs-on: ubuntu-latest
    steps:

      - name: Update the release draft and autolabel pull requests
        uses: release-drafter/release-drafter@v5
        with:
          disable-autolabeler: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
